param(
  [Parameter(Mandatory=$true)][string]$ProjectRoot,
  [string]$DbHost = "127.0.0.1",
  [int]$DbPort = 5432,
  [string]$DbName = "accredicore",
  [string]$DbUser = "postgres",
  [string]$DbPassword = "",
  [string]$SchemaPath = ""
)

$ErrorActionPreference = "Stop"

function Assert-DbInput {
  if ([string]::IsNullOrWhiteSpace($DbHost) -or (($DbHost -ne "localhost") -and ($DbHost -notmatch '^[A-Za-z0-9._-]{1,253}$'))) {
    throw "Invalid database host. Use localhost, IP address, or hostname with letters, numbers, dot, dash, underscore only."
  }

  if ($DbPort -lt 1 -or $DbPort -gt 65535) {
    throw "Invalid database port. Use a number between 1 and 65535."
  }

  if ($DbName -notmatch '^[a-z][a-z0-9_]{0,62}$') {
    throw "Invalid database name. Use lowercase letters, numbers, and underscore only; start with a letter; max 63 characters."
  }

  if ($DbUser -notmatch '^[a-z][a-z0-9_]{0,62}$') {
    throw "Invalid database user. Use lowercase letters, numbers, and underscore only; start with a letter; max 63 characters."
  }

  if ($DbPassword.Length -gt 256) {
    throw "Invalid database password. Max length is 256 characters."
  }
}

function Resolve-PsqlPath {
  $cmd = Get-Command psql -ErrorAction SilentlyContinue
  $candidatePaths = @()
  if ($cmd) { $candidatePaths += $cmd.Source }
  $candidatePaths += @(
    "C:\Program Files\PostgreSQL\17\bin\psql.exe",
    "C:\Program Files\PostgreSQL\16\bin\psql.exe",
    "C:\Program Files\PostgreSQL\15\bin\psql.exe",
    "C:\Program Files\PostgreSQL\14\bin\psql.exe",
    "C:\Program Files\PostgreSQL\13\bin\psql.exe"
  )

  foreach ($path in $candidatePaths | Select-Object -Unique) {
    if ($path -and (Test-Path -LiteralPath $path)) {
      return $path
    }
  }

  return $null
}

function Resolve-SchemaPath {
  param(
    [string]$BaseProjectRoot,
    [string]$ExplicitPath
  )

  if (-not [string]::IsNullOrWhiteSpace($ExplicitPath)) {
    if (-not (Test-Path -LiteralPath $ExplicitPath)) {
      throw "Explicit schema file was not found: $ExplicitPath"
    }
    return (Resolve-Path -LiteralPath $ExplicitPath).Path
  }

  $candidates = @(
    (Join-Path $BaseProjectRoot "database\bootstrap\local_full_schema_dump.sql"),
    (Join-Path $BaseProjectRoot "database\bootstrap\merged_supabase_migrations.sql")
  )

  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return (Resolve-Path -LiteralPath $candidate).Path
    }
  }

  $migrationDir = Join-Path $BaseProjectRoot "app-source\supabase\migrations"
  if (Test-Path -LiteralPath $migrationDir) {
    $migrationFiles = @(Get-ChildItem -LiteralPath $migrationDir -Filter "*.sql" -File | Sort-Object Name)
    if ($migrationFiles.Count -gt 0) {
      $generatedDir = Join-Path $BaseProjectRoot "database\bootstrap"
      if (-not (Test-Path -LiteralPath $generatedDir)) {
        New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null
      }

      $mergedPath = Join-Path $generatedDir "merged_supabase_migrations.sql"
      $header = @(
        "-- Generated by Arab Compliance Hub installer.",
        "-- Source: app-source/supabase/migrations",
        "-- Generated at: $(Get-Date -Format o)",
        ""
      )
      Set-Content -LiteralPath $mergedPath -Value $header -Encoding UTF8

      foreach ($file in $migrationFiles) {
        Add-Content -LiteralPath $mergedPath -Value ""
        Add-Content -LiteralPath $mergedPath -Value "-- ============================================================"
        Add-Content -LiteralPath $mergedPath -Value "-- Migration: $($file.Name)"
        Add-Content -LiteralPath $mergedPath -Value "-- ============================================================"
        Get-Content -LiteralPath $file.FullName -Raw | Add-Content -LiteralPath $mergedPath -Encoding UTF8
      }

      return (Resolve-Path -LiteralPath $mergedPath).Path
    }
  }

  throw "No bootstrap schema file was found in the cloned AccrediCore project."
}

if (-not (Test-Path -LiteralPath $ProjectRoot)) {
  throw "ProjectRoot does not exist: $ProjectRoot"
}

Assert-DbInput

$psqlCommand = Resolve-PsqlPath
if (-not $psqlCommand) {
  throw "psql was not found in PATH. Run Step 2 Install Dependencies, then run Step 1 Check Requirements again before Step 5."
}

$schemaFile = Resolve-SchemaPath -BaseProjectRoot $ProjectRoot -ExplicitPath $SchemaPath
$env:PGPASSWORD = $DbPassword

try {
  Write-Host "STEP 5 RESULT"
  Write-Host "- Project root: $ProjectRoot"
  Write-Host "- Database target: ${DbHost}:${DbPort} / $DbName"
  Write-Host "- Schema file: $schemaFile"

  $existsOutput = & $psqlCommand -h $DbHost -p $DbPort -U $DbUser -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname = '$DbName';" 2>&1
  if ($LASTEXITCODE -ne 0) {
    throw "Could not query PostgreSQL server. Details: $existsOutput"
  }

  $dbExists = ($existsOutput | Out-String).Trim() -eq "1"
  if (-not $dbExists) {
    $createOutput = & $psqlCommand -h $DbHost -p $DbPort -U $DbUser -d postgres -v ON_ERROR_STOP=1 -c "CREATE DATABASE ""$DbName"";" 2>&1
    if ($LASTEXITCODE -ne 0) {
      throw "Could not create database '$DbName'. Details: $createOutput"
    }
    Write-Host "- Database created successfully."
  } else {
    Write-Host "- Database already exists. Re-importing structure into the existing database."
  }

  $importOutput = & $psqlCommand -h $DbHost -p $DbPort -U $DbUser -d $DbName -v ON_ERROR_STOP=1 -f $schemaFile 2>&1
  if ($LASTEXITCODE -ne 0) {
    throw "Schema import failed. Details: $importOutput"
  }

  Write-Host "- Database structure import completed successfully."
  Write-Host "- Running smoke test: database connection and table visibility."

  $smokeSql = "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';"
  $smokeOutput = & $psqlCommand -h $DbHost -p $DbPort -U $DbUser -d $DbName -tAc $smokeSql 2>&1
  if ($LASTEXITCODE -ne 0) {
    throw "Database smoke test failed. Details: $smokeOutput"
  }

  $tableCount = ($smokeOutput | Out-String).Trim()
  if ([string]::IsNullOrWhiteSpace($tableCount) -or -not ($tableCount -match '^\d+$')) {
    throw "Database smoke test returned an unexpected result: $smokeOutput"
  }

  Write-Host "- Database connection smoke test passed."
  Write-Host "- Public table/view objects detected: $tableCount"
  Write-Host "- Step 5 completed. Continue to Step 6 to import .env and activation.json."
  exit 0
}
finally {
  Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
}
