param(
  [Parameter(Mandatory=$true)][string]$ProjectRoot,
  [string]$DbHost = "127.0.0.1",
  [int]$DbPort = 5432,
  [string]$DbName = "accredicore",
  [string]$DbUser = "postgres",
  [string]$DbPassword = "",
  [string]$SchemaPath = ""
)

$ErrorActionPreference = "Stop"

function Assert-DbInput {
  if ([string]::IsNullOrWhiteSpace($DbHost) -or (($DbHost -ne "localhost") -and ($DbHost -notmatch '^[A-Za-z0-9._-]{1,253}$'))) {
    throw "Invalid database host. Use localhost, IP address, or hostname with letters, numbers, dot, dash, underscore only."
  }

  if ($DbPort -lt 1 -or $DbPort -gt 65535) {
    throw "Invalid database port. Use a number between 1 and 65535."
  }

  if ($DbName -notmatch '^[a-z][a-z0-9_]{0,62}$') {
    throw "Invalid database name. Use lowercase letters, numbers, and underscore only; start with a letter; max 63 characters."
  }

  if ($DbUser -notmatch '^[a-z][a-z0-9_]{0,62}$') {
    throw "Invalid database user. Use lowercase letters, numbers, and underscore only; start with a letter; max 63 characters."
  }

  if ([string]::IsNullOrWhiteSpace($DbPassword) -or $DbPassword.Length -lt 8 -or $DbPassword.Length -gt 256) {
    throw "Invalid database password. Password is required and must be 8-256 characters."
  }

  if (($DbPassword -notmatch '[a-z]') -or ($DbPassword -notmatch '[A-Z]') -or ($DbPassword -notmatch '\d') -or ($DbPassword -notmatch '[^A-Za-z0-9]')) {
    throw "Invalid database password. Use uppercase, lowercase, number, and symbol such as #, $, &, !, or @."
  }
}

function Resolve-PsqlPath {
  $cmd = Get-Command psql -ErrorAction SilentlyContinue
  $candidatePaths = @()
  if ($cmd) { $candidatePaths += $cmd.Source }
  $candidatePaths += @(
    "C:\Program Files\PostgreSQL\17\bin\psql.exe",
    "C:\Program Files\PostgreSQL\16\bin\psql.exe",
    "C:\Program Files\PostgreSQL\15\bin\psql.exe",
    "C:\Program Files\PostgreSQL\14\bin\psql.exe",
    "C:\Program Files\PostgreSQL\13\bin\psql.exe"
  )

  foreach ($root in @(
    "C:\Program Files\PostgreSQL",
    "C:\Program Files (x86)\PostgreSQL",
    "$env:LOCALAPPDATA\Programs\PostgreSQL",
    "$env:APPDATA\PostgreSQL"
  )) {
    if (Test-Path -LiteralPath $root) {
      $candidatePaths += Get-ChildItem -LiteralPath $root -Recurse -Filter "psql.exe" -ErrorAction SilentlyContinue |
        Select-Object -ExpandProperty FullName
    }
  }

  foreach ($path in $candidatePaths | Select-Object -Unique) {
    if ($path -and (Test-Path -LiteralPath $path)) {
      return $path
    }
  }

  return $null
}

function Resolve-SchemaPath {
  param(
    [string]$BaseProjectRoot,
    [string]$ExplicitPath
  )

  if (-not [string]::IsNullOrWhiteSpace($ExplicitPath)) {
    if (-not (Test-Path -LiteralPath $ExplicitPath)) {
      throw "Explicit schema file was not found: $ExplicitPath"
    }
    return (Resolve-Path -LiteralPath $ExplicitPath).Path
  }

  $candidates = @(
    (Join-Path $BaseProjectRoot "database\bootstrap\local_full_schema_dump.sql"),
    (Join-Path $BaseProjectRoot "database\bootstrap\merged_supabase_migrations.sql")
  )

  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return (Resolve-Path -LiteralPath $candidate).Path
    }
  }

  $migrationDir = Join-Path $BaseProjectRoot "app-source\supabase\migrations"
  if (Test-Path -LiteralPath $migrationDir) {
    $migrationFiles = @(Get-ChildItem -LiteralPath $migrationDir -Filter "*.sql" -File | Sort-Object Name)
    if ($migrationFiles.Count -gt 0) {
      $generatedDir = Join-Path $BaseProjectRoot "database\bootstrap"
      if (-not (Test-Path -LiteralPath $generatedDir)) {
        New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null
      }

      $mergedPath = Join-Path $generatedDir "merged_supabase_migrations.sql"
      $header = @(
        "-- Generated by Arab Compliance Hub installer.",
        "-- Source: app-source/supabase/migrations",
        "-- Generated at: $(Get-Date -Format o)",
        ""
      )
      Set-Content -LiteralPath $mergedPath -Value $header -Encoding UTF8

      foreach ($file in $migrationFiles) {
        Add-Content -LiteralPath $mergedPath -Value ""
        Add-Content -LiteralPath $mergedPath -Value "-- ============================================================"
        Add-Content -LiteralPath $mergedPath -Value "-- Migration: $($file.Name)"
        Add-Content -LiteralPath $mergedPath -Value "-- ============================================================"
        Get-Content -LiteralPath $file.FullName -Raw | Add-Content -LiteralPath $mergedPath -Encoding UTF8
      }

      return (Resolve-Path -LiteralPath $mergedPath).Path
    }
  }

  throw "No bootstrap schema file was found in the cloned AccrediCore project."
}

function Format-PsqlError {
  param(
    [string]$Context,
    [object]$Details
  )

  $text = ($Details | Out-String).Trim()
  if ($text -match "no password supplied|password authentication failed") {
    return "$Context PostgreSQL requires a valid password for user '$DbUser'. Enter the PostgreSQL password in the Database password field, then run Step 5A/5B again. Details: $text"
  }

  return "$Context Details: $text"
}

$script:LastPsqlExitCode = 0
function Invoke-Psql {
  param(
    [Parameter(Mandatory=$true)][string[]]$Arguments
  )

  $oldPreference = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    $output = & $psqlCommand @Arguments 2>&1 | ForEach-Object {
      if ($_ -is [System.Management.Automation.ErrorRecord]) {
        $_.Exception.Message
      } else {
        $_
      }
    }
    $script:LastPsqlExitCode = $LASTEXITCODE
    return $output
  }
  finally {
    $ErrorActionPreference = $oldPreference
  }
}

if (-not (Test-Path -LiteralPath $ProjectRoot)) {
  throw "ProjectRoot does not exist: $ProjectRoot"
}

Assert-DbInput

$psqlCommand = Resolve-PsqlPath
if (-not $psqlCommand) {
  throw "PostgreSQL Client (psql) was not found on this device. The installer searched PATH, Program Files, Program Files (x86), and common user install locations. Run Step 2 Install Dependencies, restart the installer if needed, then run Step 1 Check Requirements again before Step 5."
}

$schemaFile = Resolve-SchemaPath -BaseProjectRoot $ProjectRoot -ExplicitPath $SchemaPath
$env:PGPASSWORD = $DbPassword

try {
  Write-Host "STEP 5 RESULT"
  Write-Host "- Project root: $ProjectRoot"
  Write-Host "- Database target: ${DbHost}:${DbPort} / $DbName"
  Write-Host "- Schema file: $schemaFile"

  $existsOutput = Invoke-Psql -Arguments @("-w", "-h", $DbHost, "-p", "$DbPort", "-U", $DbUser, "-d", "postgres", "-tAc", "SELECT 1 FROM pg_database WHERE datname = '$DbName';")
  if ($script:LastPsqlExitCode -ne 0) {
    throw (Format-PsqlError -Context "Could not query PostgreSQL server." -Details $existsOutput)
  }

  $dbExists = ($existsOutput | Out-String).Trim() -eq "1"
  if (-not $dbExists) {
    $createOutput = Invoke-Psql -Arguments @("-w", "-h", $DbHost, "-p", "$DbPort", "-U", $DbUser, "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-c", "CREATE DATABASE ""$DbName"";")
    if ($script:LastPsqlExitCode -ne 0) {
      throw (Format-PsqlError -Context "Could not create database '$DbName'." -Details $createOutput)
    }
    Write-Host "- Database created successfully."
  } else {
    Write-Host "- Database already exists. Resetting application schemas before re-import."
    $disconnectSql = "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '$DbName' AND pid <> pg_backend_pid();"
    $disconnectOutput = Invoke-Psql -Arguments @("-w", "-h", $DbHost, "-p", "$DbPort", "-U", $DbUser, "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-c", $disconnectSql)
    if ($script:LastPsqlExitCode -ne 0) {
      throw (Format-PsqlError -Context "Could not prepare existing database for reset." -Details $disconnectOutput)
    }

    $resetSql = @"
SET lock_timeout = '15s';
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO public;
"@
    $resetOutput = Invoke-Psql -Arguments @("-w", "-h", $DbHost, "-p", "$DbPort", "-U", $DbUser, "-d", $DbName, "-v", "ON_ERROR_STOP=1", "-c", $resetSql)
    if ($script:LastPsqlExitCode -ne 0) {
      throw (Format-PsqlError -Context "Could not reset existing database schemas safely." -Details $resetOutput)
    }
    Write-Host "- Existing application schemas reset successfully."
  }

  Write-Host "- Step 5A: importing bundled database structure."
  $importOutput = Invoke-Psql -Arguments @("-w", "-h", $DbHost, "-p", "$DbPort", "-U", $DbUser, "-d", $DbName, "-v", "ON_ERROR_STOP=1", "-f", $schemaFile)
  if ($script:LastPsqlExitCode -ne 0) {
    throw (Format-PsqlError -Context "Schema import failed." -Details $importOutput)
  }

  Write-Host "- Database structure import completed successfully."
  Write-Host "- Step 5B: running smoke test for database connection and table visibility."

  $smokeSql = "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';"
  $smokeOutput = Invoke-Psql -Arguments @("-w", "-h", $DbHost, "-p", "$DbPort", "-U", $DbUser, "-d", $DbName, "-tAc", $smokeSql)
  if ($script:LastPsqlExitCode -ne 0) {
    throw (Format-PsqlError -Context "Database smoke test failed." -Details $smokeOutput)
  }

  $tableCount = ($smokeOutput | Out-String).Trim()
  if ([string]::IsNullOrWhiteSpace($tableCount) -or -not ($tableCount -match '^\d+$')) {
    throw "Database smoke test returned an unexpected result: $smokeOutput"
  }

  Write-Host "- Database connection smoke test passed."
  Write-Host "- Public table/view objects detected: $tableCount"
  Write-Host "- Step 5 completed. Continue to Step 6 to import .env and activation.json."
  exit 0
}
catch {
  Write-Host ("ERROR: " + $_.Exception.Message)
  exit 1
}
finally {
  Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
}
